# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jakchyla/src/irrigation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jakchyla/src/irrigation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakchyla/src/irrigation/CMakeFiles /home/jakchyla/src/irrigation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakchyla/src/irrigation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named irrigation

# Build rule for target.
irrigation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irrigation
.PHONY : irrigation

# fast build rule for target.
irrigation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/build
.PHONY : irrigation/fast

#=============================================================================
# Target rules for targets named STM32_Drivers

# Build rule for target.
STM32_Drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STM32_Drivers
.PHONY : STM32_Drivers

# fast build rule for target.
STM32_Drivers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build.make cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build
.PHONY : STM32_Drivers/fast

Core/Src/irrigation.obj: Core/Src/irrigation.c.obj
.PHONY : Core/Src/irrigation.obj

# target to build an object file
Core/Src/irrigation.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/irrigation.c.obj
.PHONY : Core/Src/irrigation.c.obj

Core/Src/irrigation.i: Core/Src/irrigation.c.i
.PHONY : Core/Src/irrigation.i

# target to preprocess a source file
Core/Src/irrigation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/irrigation.c.i
.PHONY : Core/Src/irrigation.c.i

Core/Src/irrigation.s: Core/Src/irrigation.c.s
.PHONY : Core/Src/irrigation.s

# target to generate assembly for a file
Core/Src/irrigation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/irrigation.c.s
.PHONY : Core/Src/irrigation.c.s

Core/Src/main.obj: Core/Src/main.c.obj
.PHONY : Core/Src/main.obj

# target to build an object file
Core/Src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/main.c.obj
.PHONY : Core/Src/main.c.obj

Core/Src/main.i: Core/Src/main.c.i
.PHONY : Core/Src/main.i

# target to preprocess a source file
Core/Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/main.c.i
.PHONY : Core/Src/main.c.i

Core/Src/main.s: Core/Src/main.c.s
.PHONY : Core/Src/main.s

# target to generate assembly for a file
Core/Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/main.c.s
.PHONY : Core/Src/main.c.s

Core/Src/screen.obj: Core/Src/screen.c.obj
.PHONY : Core/Src/screen.obj

# target to build an object file
Core/Src/screen.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/screen.c.obj
.PHONY : Core/Src/screen.c.obj

Core/Src/screen.i: Core/Src/screen.c.i
.PHONY : Core/Src/screen.i

# target to preprocess a source file
Core/Src/screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/screen.c.i
.PHONY : Core/Src/screen.c.i

Core/Src/screen.s: Core/Src/screen.c.s
.PHONY : Core/Src/screen.s

# target to generate assembly for a file
Core/Src/screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/screen.c.s
.PHONY : Core/Src/screen.c.s

Core/Src/ssd1306.obj: Core/Src/ssd1306.c.obj
.PHONY : Core/Src/ssd1306.obj

# target to build an object file
Core/Src/ssd1306.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306.c.obj
.PHONY : Core/Src/ssd1306.c.obj

Core/Src/ssd1306.i: Core/Src/ssd1306.c.i
.PHONY : Core/Src/ssd1306.i

# target to preprocess a source file
Core/Src/ssd1306.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306.c.i
.PHONY : Core/Src/ssd1306.c.i

Core/Src/ssd1306.s: Core/Src/ssd1306.c.s
.PHONY : Core/Src/ssd1306.s

# target to generate assembly for a file
Core/Src/ssd1306.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306.c.s
.PHONY : Core/Src/ssd1306.c.s

Core/Src/ssd1306_fonts.obj: Core/Src/ssd1306_fonts.c.obj
.PHONY : Core/Src/ssd1306_fonts.obj

# target to build an object file
Core/Src/ssd1306_fonts.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306_fonts.c.obj
.PHONY : Core/Src/ssd1306_fonts.c.obj

Core/Src/ssd1306_fonts.i: Core/Src/ssd1306_fonts.c.i
.PHONY : Core/Src/ssd1306_fonts.i

# target to preprocess a source file
Core/Src/ssd1306_fonts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306_fonts.c.i
.PHONY : Core/Src/ssd1306_fonts.c.i

Core/Src/ssd1306_fonts.s: Core/Src/ssd1306_fonts.c.s
.PHONY : Core/Src/ssd1306_fonts.s

# target to generate assembly for a file
Core/Src/ssd1306_fonts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306_fonts.c.s
.PHONY : Core/Src/ssd1306_fonts.c.s

Core/Src/ssd1306_tests.obj: Core/Src/ssd1306_tests.c.obj
.PHONY : Core/Src/ssd1306_tests.obj

# target to build an object file
Core/Src/ssd1306_tests.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306_tests.c.obj
.PHONY : Core/Src/ssd1306_tests.c.obj

Core/Src/ssd1306_tests.i: Core/Src/ssd1306_tests.c.i
.PHONY : Core/Src/ssd1306_tests.i

# target to preprocess a source file
Core/Src/ssd1306_tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306_tests.c.i
.PHONY : Core/Src/ssd1306_tests.c.i

Core/Src/ssd1306_tests.s: Core/Src/ssd1306_tests.c.s
.PHONY : Core/Src/ssd1306_tests.s

# target to generate assembly for a file
Core/Src/ssd1306_tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/ssd1306_tests.c.s
.PHONY : Core/Src/ssd1306_tests.c.s

Core/Src/stm32l4xx_hal_msp.obj: Core/Src/stm32l4xx_hal_msp.c.obj
.PHONY : Core/Src/stm32l4xx_hal_msp.obj

# target to build an object file
Core/Src/stm32l4xx_hal_msp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/stm32l4xx_hal_msp.c.obj
.PHONY : Core/Src/stm32l4xx_hal_msp.c.obj

Core/Src/stm32l4xx_hal_msp.i: Core/Src/stm32l4xx_hal_msp.c.i
.PHONY : Core/Src/stm32l4xx_hal_msp.i

# target to preprocess a source file
Core/Src/stm32l4xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/stm32l4xx_hal_msp.c.i
.PHONY : Core/Src/stm32l4xx_hal_msp.c.i

Core/Src/stm32l4xx_hal_msp.s: Core/Src/stm32l4xx_hal_msp.c.s
.PHONY : Core/Src/stm32l4xx_hal_msp.s

# target to generate assembly for a file
Core/Src/stm32l4xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/stm32l4xx_hal_msp.c.s
.PHONY : Core/Src/stm32l4xx_hal_msp.c.s

Core/Src/stm32l4xx_it.obj: Core/Src/stm32l4xx_it.c.obj
.PHONY : Core/Src/stm32l4xx_it.obj

# target to build an object file
Core/Src/stm32l4xx_it.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/stm32l4xx_it.c.obj
.PHONY : Core/Src/stm32l4xx_it.c.obj

Core/Src/stm32l4xx_it.i: Core/Src/stm32l4xx_it.c.i
.PHONY : Core/Src/stm32l4xx_it.i

# target to preprocess a source file
Core/Src/stm32l4xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/stm32l4xx_it.c.i
.PHONY : Core/Src/stm32l4xx_it.c.i

Core/Src/stm32l4xx_it.s: Core/Src/stm32l4xx_it.c.s
.PHONY : Core/Src/stm32l4xx_it.s

# target to generate assembly for a file
Core/Src/stm32l4xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/stm32l4xx_it.c.s
.PHONY : Core/Src/stm32l4xx_it.c.s

Core/Src/syscalls.obj: Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.obj

# target to build an object file
Core/Src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.c.obj

Core/Src/syscalls.i: Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.i

# target to preprocess a source file
Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.c.i

Core/Src/syscalls.s: Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.s

# target to generate assembly for a file
Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.c.s

Core/Src/sysmem.obj: Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.obj

# target to build an object file
Core/Src/sysmem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.c.obj

Core/Src/sysmem.i: Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.i

# target to preprocess a source file
Core/Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.c.i

Core/Src/sysmem.s: Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.s

# target to generate assembly for a file
Core/Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.c.s

startup_stm32l412xx.obj: startup_stm32l412xx.s.obj
.PHONY : startup_stm32l412xx.obj

# target to build an object file
startup_stm32l412xx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irrigation.dir/build.make CMakeFiles/irrigation.dir/startup_stm32l412xx.s.obj
.PHONY : startup_stm32l412xx.s.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... STM32_Drivers"
	@echo "... irrigation"
	@echo "... Core/Src/irrigation.obj"
	@echo "... Core/Src/irrigation.i"
	@echo "... Core/Src/irrigation.s"
	@echo "... Core/Src/main.obj"
	@echo "... Core/Src/main.i"
	@echo "... Core/Src/main.s"
	@echo "... Core/Src/screen.obj"
	@echo "... Core/Src/screen.i"
	@echo "... Core/Src/screen.s"
	@echo "... Core/Src/ssd1306.obj"
	@echo "... Core/Src/ssd1306.i"
	@echo "... Core/Src/ssd1306.s"
	@echo "... Core/Src/ssd1306_fonts.obj"
	@echo "... Core/Src/ssd1306_fonts.i"
	@echo "... Core/Src/ssd1306_fonts.s"
	@echo "... Core/Src/ssd1306_tests.obj"
	@echo "... Core/Src/ssd1306_tests.i"
	@echo "... Core/Src/ssd1306_tests.s"
	@echo "... Core/Src/stm32l4xx_hal_msp.obj"
	@echo "... Core/Src/stm32l4xx_hal_msp.i"
	@echo "... Core/Src/stm32l4xx_hal_msp.s"
	@echo "... Core/Src/stm32l4xx_it.obj"
	@echo "... Core/Src/stm32l4xx_it.i"
	@echo "... Core/Src/stm32l4xx_it.s"
	@echo "... Core/Src/syscalls.obj"
	@echo "... Core/Src/syscalls.i"
	@echo "... Core/Src/syscalls.s"
	@echo "... Core/Src/sysmem.obj"
	@echo "... Core/Src/sysmem.i"
	@echo "... Core/Src/sysmem.s"
	@echo "... startup_stm32l412xx.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

